name 'windows_webserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures windows_webserver'
long_description 'Installs/Configures windows_webserver'
version '0.1.0'
