name 'WindowsMachineConfiguration'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures WindowsMachineConfiguration'
long_description 'Installs/Configures WindowsMachineConfiguration'
version '0.1.0'
